### ISSUE TITLE
Not able to load the custom modules

### ISSUE THREAD

**Issue by vwucher** [gangwug/CYCLOPSv3.0.2.1#1]
Dear @gangwug,

I am trying to run CYCLOPS using your version of the program on your example dataset but I get the following error:

```
CYCLOPSv3.0.2.1-master$ julia -p 5 runCYCLOPS_Eigen.jl --cycdir /home/valentin/programme/CYCLOPSv3.0.2.1-master/RonCYCLOPSv3/ --infile example.ToRunCYCLOPS.csv --seedfile clockList.csv --outdir ~/test/cyclops/
ERROR: LoadError: ArgumentError: Package CYCLOPS_2a_AutoEncoderModule not found in current path:
- Run `import Pkg; Pkg.add("CYCLOPS_2a_AutoEncoderModule")` to install the CYCLOPS_2a_AutoEncoderModule package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] exec_options(::Base.JLOptions) at ./client.jl:296
 [5] _start() at ./client.jl:506
in expression starting at /home/valentin/programme/CYCLOPSv3.0.2.1-master/runCYCLOPS_Eigen.jl:56
```

I think I get this error because julia cannot load the modules. I am sorry but I am totally new to julia so it is maybe a trivial question...
I am using julia version 1.5.3, the error can come from the difference of version?

Thanks you in advance for your help.
Have a nice day,
Valentin Wucher

**Comment by gangwug** [comment]
Hi Valentin, 
Did you try julia version 0.3.12?

**Comment by vwucher** [comment]
Hi @gangwug,

Thanks a lot for your answer.
I was able to find the version 0.3.12 and `runCYCLOPS_Eigen.jl` run perfectly as the others scripts. So it was because of the version of julia.

Thanks for your help.
Valentin
